import { NextResponse } from "next/server";

import { requireSessionActor, toErrorResponse } from "@/lib/server/api-route";
import { query } from "@/lib/server/db";
import { ensureBackendReady } from "@/lib/server/smart-api";

type PublicTableRow = {
  table_name: string;
};

type TableColumnRow = {
  column_name: string;
  data_type: string;
  is_not_null: boolean;
  column_default: string | null;
  ordinal_position: number;
};

type PrimaryKeyColumnRow = {
  column_name: string;
  order_index: number;
};

function quoteIdent(identifier: string) {
  return `"${identifier.replace(/"/g, "\"\"")}"`;
}

function toSqlLiteral(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "boolean") return value ? "TRUE" : "FALSE";
  if (typeof value === "number") {
    if (!Number.isFinite(value)) return "NULL";
    return String(value);
  }
  if (typeof value === "bigint") {
    return value.toString();
  }
  if (value instanceof Date) {
    const iso = value.toISOString().replace("T", " ").replace("Z", "+00");
    return `'${iso.replace(/'/g, "''")}'`;
  }
  if (Buffer.isBuffer(value)) {
    return `E'\\\\x${value.toString("hex")}'::bytea`;
  }
  if (typeof value === "object") {
    const json = JSON.stringify(value);
    return `'${json.replace(/'/g, "''")}'::jsonb`;
  }
  return `'${String(value).replace(/'/g, "''")}'`;
}

function buildTimestampForFilename() {
  const now = new Date();
  const pad = (value: number) => String(value).padStart(2, "0");
  const year = now.getUTCFullYear();
  const month = pad(now.getUTCMonth() + 1);
  const day = pad(now.getUTCDate());
  const hours = pad(now.getUTCHours());
  const minutes = pad(now.getUTCMinutes());
  const seconds = pad(now.getUTCSeconds());
  return `${year}${month}${day}-${hours}${minutes}${seconds}`;
}

async function buildSqlBackup(actorEmail: string) {
  const tablesResult = await query<PublicTableRow>(
    `
      SELECT table_name
      FROM information_schema.tables
      WHERE table_schema = 'public'
        AND table_type = 'BASE TABLE'
      ORDER BY table_name ASC
    `,
  );
  const tables = tablesResult.rows.map((row) => row.table_name).filter(Boolean);

  const lines: string[] = [];
  lines.push("-- Smart Cluster SQL Backup");
  lines.push(`-- Generated at: ${new Date().toISOString()}`);
  lines.push(`-- Generated by: ${actorEmail}`);
  lines.push("-- Scope: public schema (structure + data)");
  lines.push("");
  lines.push("BEGIN;");
  lines.push("");

  for (const tableName of tables) {
    const qualifiedRegclass = `public.${tableName}`;
    const tableIdent = quoteIdent(tableName);

    const columnsResult = await query<TableColumnRow>(
      `
        SELECT
          a.attname AS column_name,
          pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
          a.attnotnull AS is_not_null,
          pg_get_expr(ad.adbin, ad.adrelid) AS column_default,
          a.attnum AS ordinal_position
        FROM pg_attribute a
        JOIN pg_class c ON c.oid = a.attrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
        WHERE n.nspname = 'public'
          AND c.relname = $1
          AND a.attnum > 0
          AND NOT a.attisdropped
        ORDER BY a.attnum ASC
      `,
      [tableName],
    );

    if (!columnsResult.rows.length) continue;

    const pkResult = await query<PrimaryKeyColumnRow>(
      `
        SELECT
          a.attname AS column_name,
          cols.ord::int AS order_index
        FROM pg_constraint ct
        JOIN pg_class c ON c.oid = ct.conrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        JOIN unnest(ct.conkey) WITH ORDINALITY AS cols(attnum, ord) ON TRUE
        JOIN pg_attribute a ON a.attrelid = ct.conrelid AND a.attnum = cols.attnum
        WHERE n.nspname = 'public'
          AND c.relname = $1
          AND ct.contype = 'p'
        ORDER BY cols.ord ASC
      `,
      [tableName],
    );

    lines.push(`--`);
    lines.push(`-- Table: public.${tableName}`);
    lines.push(`--`);
    lines.push(`CREATE TABLE IF NOT EXISTS ${tableIdent} (`);

    const createLines = columnsResult.rows.map((column) => {
      const chunks = [quoteIdent(column.column_name), column.data_type];
      if (column.column_default) {
        chunks.push(`DEFAULT ${column.column_default}`);
      }
      if (column.is_not_null) {
        chunks.push("NOT NULL");
      }
      return `  ${chunks.join(" ")}`;
    });

    if (pkResult.rows.length) {
      const pkColumns = pkResult.rows
        .sort((a, b) => a.order_index - b.order_index)
        .map((column) => quoteIdent(column.column_name))
        .join(", ");
      createLines.push(`  PRIMARY KEY (${pkColumns})`);
    }

    lines.push(createLines.join(",\n"));
    lines.push(");");
    lines.push("");

    const rowsResult = await query<Record<string, unknown>>(`SELECT * FROM ${tableIdent}`);
    if (!rowsResult.rows.length) {
      lines.push(`-- No rows for ${tableName}`);
      lines.push("");
      continue;
    }

    const orderedColumns = columnsResult.rows.map((column) => column.column_name);
    const insertColumnList = orderedColumns.map((column) => quoteIdent(column)).join(", ");

    for (const row of rowsResult.rows) {
      const values = orderedColumns.map((column) => toSqlLiteral(row[column])).join(", ");
      lines.push(`INSERT INTO ${tableIdent} (${insertColumnList}) VALUES (${values});`);
    }
    lines.push("");

    // Ensure sequence values keep up with explicit INSERT ids for serial/identity-like columns.
    const sequenceResult = await query<{ sequence_name: string; column_name: string }>(
      `
        SELECT
          pg_get_serial_sequence($1, a.attname) AS sequence_name,
          a.attname AS column_name
        FROM pg_attribute a
        JOIN pg_class c ON c.oid = a.attrelid
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relname = $2
          AND a.attnum > 0
          AND NOT a.attisdropped
      `,
      [qualifiedRegclass, tableName],
    );

    for (const sequence of sequenceResult.rows) {
      if (!sequence.sequence_name) continue;
      const columnIdent = quoteIdent(sequence.column_name);
      const escapedSequenceName = sequence.sequence_name.replace(/'/g, "''");
      lines.push(
        `SELECT setval('${escapedSequenceName}', COALESCE((SELECT MAX(${columnIdent}) FROM ${tableIdent}), 1), TRUE);`,
      );
    }
    if (sequenceResult.rows.length) {
      lines.push("");
    }
  }

  lines.push("COMMIT;");
  lines.push("");
  return lines.join("\n");
}

export const runtime = "nodejs";

export async function GET(request: Request) {
  try {
    await ensureBackendReady();
    const sessionUser = await requireSessionActor(request, ["superadmin"]);
    const sql = await buildSqlBackup(sessionUser.email);
    const filename = `smart-cluster-backup-${buildTimestampForFilename()}.sql`;

    return new NextResponse(sql, {
      status: 200,
      headers: {
        "Content-Type": "application/sql; charset=utf-8",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (error) {
    return toErrorResponse(error);
  }
}
